export interface DistrictData {
  name: string;
  courts: string[];
  policeStations: string[];
}

export const KERALA_DISTRICTS: Record<string, DistrictData> = {
  Thiruvananthapuram: {
    name: "Thiruvananthapuram",
    courts: [
      "District Court, Thiruvananthapuram",
      "Sub Court, Attingal",
      "Sub Court, Neyyattinkara",
      "Munsiff Court, Thiruvananthapuram",
      "Munsiff Court, Attingal",
      "Munsiff Court, Neyyattinkara",
      "Munsiff Court, Nedumangad",
      "Munsiff Court, Chirayinkeezhu",
      "Family Court, Thiruvananthapuram",
      "Motor Accident Claims Tribunal, Thiruvananthapuram",
      "Judicial First Class Magistrate Court I, Thiruvananthapuram",
      "Judicial First Class Magistrate Court II, Thiruvananthapuram",
      "Chief Judicial Magistrate Court, Thiruvananthapuram",
      "Sessions Court, Thiruvananthapuram",
      "Additional District Court, Thiruvananthapuram",
      "Labour Court, Thiruvananthapuram",
      "Consumer Disputes Redressal Forum, Thiruvananthapuram",
    ],
    policeStations: [
      "Museum Police Station",
      "Thampanoor Police Station",
      "Fort Police Station",
      "Pettah Police Station",
      "Cantonment Police Station",
      "Valiyathura Police Station",
      "Shanghumughom Police Station",
      "Vanchiyoor Police Station",
      "Nemom Police Station",
      "Poojappura Police Station",
      "Peroorkada Police Station",
      "Vattiyoorkavu Police Station",
      "Sreekaryam Police Station",
      "Mannanthala Police Station",
      "Kazhakkoottam Police Station",
      "Pangode Police Station",
      "Balaramapuram Police Station",
      "Vizhinjam Police Station",
      "Kovalam Police Station",
      "Attingal Police Station",
      "Varkala Police Station",
      "Chirayinkeezhu Police Station",
      "Neyyattinkara Police Station",
      "Nedumangad Police Station",
      "Aryanad Police Station",
      "Pothencode Police Station",
      "Vellanad Police Station",
      "Kilimanoor Police Station",
      "Parassala Police Station",
      "Venjaramoodu Police Station",
    ],
  },
  Kollam: {
    name: "Kollam",
    courts: [
      "District Court, Kollam",
      "Sub Court, Kollam",
      "Sub Court, Karunagappally",
      "Sub Court, Punalur",
      "Munsiff Court, Kollam",
      "Munsiff Court, Karunagappally",
      "Munsiff Court, Punalur",
      "Munsiff Court, Kottarakkara",
      "Munsiff Court, Pathanapuram",
      "Family Court, Kollam",
      "Motor Accident Claims Tribunal, Kollam",
      "Chief Judicial Magistrate Court, Kollam",
      "Sessions Court, Kollam",
      "Additional District Court, Kollam",
      "Consumer Disputes Redressal Forum, Kollam",
    ],
    policeStations: [
      "Kollam East Police Station",
      "Kollam West Police Station",
      "Sakthikulangara Police Station",
      "Eravipuram Police Station",
      "Chavara Police Station",
      "Karunagappally Police Station",
      "Oachira Police Station",
      "Sasthamcotta Police Station",
      "Kunnathur Police Station",
      "Kottarakkara Police Station",
      "Anchal Police Station",
      "Punalur Police Station",
      "Pathanapuram Police Station",
      "Kundara Police Station",
      "Chathannoor Police Station",
      "Paravur Police Station",
      "Nedumpana Police Station",
      "Chadayamangalam Police Station",
      "Kadakkal Police Station",
      "Yeroor Police Station",
      "Sooranadu Police Station",
      "Kulathupuzha Police Station",
    ],
  },
  Pathanamthitta: {
    name: "Pathanamthitta",
    courts: [
      "District Court, Pathanamthitta",
      "Sub Court, Tiruvalla",
      "Sub Court, Adoor",
      "Munsiff Court, Pathanamthitta",
      "Munsiff Court, Tiruvalla",
      "Munsiff Court, Adoor",
      "Munsiff Court, Ranni",
      "Munsiff Court, Kozhencherry",
      "Family Court, Pathanamthitta",
      "Chief Judicial Magistrate Court, Pathanamthitta",
      "Sessions Court, Pathanamthitta",
      "Consumer Disputes Redressal Forum, Pathanamthitta",
    ],
    policeStations: [
      "Pathanamthitta Police Station",
      "Tiruvalla Police Station",
      "Adoor Police Station",
      "Pandalam Police Station",
      "Kozhencherry Police Station",
      "Ranni Police Station",
      "Konni Police Station",
      "Thiruvalla East Police Station",
      "Eraviperoor Police Station",
      "Aranmula Police Station",
      "Mallappally Police Station",
      "Kumbanad Police Station",
      "Pramadom Police Station",
      "Seethathodu Police Station",
      "Chittar Police Station",
      "Perunad Police Station",
      "Sabarimala Police Station",
    ],
  },
  Alappuzha: {
    name: "Alappuzha",
    courts: [
      "District Court, Alappuzha",
      "Sub Court, Alappuzha",
      "Sub Court, Cherthala",
      "Sub Court, Mavelikkara",
      "Munsiff Court, Alappuzha",
      "Munsiff Court, Ambalapuzha",
      "Munsiff Court, Cherthala",
      "Munsiff Court, Chengannur",
      "Munsiff Court, Mavelikkara",
      "Munsiff Court, Haripad",
      "Family Court, Alappuzha",
      "Chief Judicial Magistrate Court, Alappuzha",
      "Sessions Court, Alappuzha",
      "Motor Accident Claims Tribunal, Alappuzha",
      "Consumer Disputes Redressal Forum, Alappuzha",
    ],
    policeStations: [
      "Alappuzha North Police Station",
      "Alappuzha South Police Station",
      "Ambalapuzha Police Station",
      "Punnapra Police Station",
      "Cherthala Police Station",
      "Aroor Police Station",
      "Thuravoor Police Station",
      "Mannancherry Police Station",
      "Kanjikuzhi Police Station",
      "Haripad Police Station",
      "Kayamkulam Police Station",
      "Mavelikkara Police Station",
      "Nooranad Police Station",
      "Chengannur Police Station",
      "Pandanad Police Station",
      "Bharanikavu Police Station",
      "Mavelikara Police Station",
      "Thiruvalla Police Station",
      "Budhanoor Police Station",
      "Ramankary Police Station",
    ],
  },
  Kottayam: {
    name: "Kottayam",
    courts: [
      "District Court, Kottayam",
      "Sub Court, Kottayam",
      "Sub Court, Meenachil (Pala)",
      "Sub Court, Vaikom",
      "Munsiff Court, Kottayam",
      "Munsiff Court, Ettumanoor",
      "Munsiff Court, Pala",
      "Munsiff Court, Vaikom",
      "Munsiff Court, Changanacherry",
      "Family Court, Kottayam",
      "Chief Judicial Magistrate Court, Kottayam",
      "Sessions Court, Kottayam",
      "Motor Accident Claims Tribunal, Kottayam",
      "Consumer Disputes Redressal Forum, Kottayam",
    ],
    policeStations: [
      "Kottayam West Police Station",
      "Kottayam East Police Station",
      "Kumarakom Police Station",
      "Changanacherry Police Station",
      "Vaikom Police Station",
      "Ettumanoor Police Station",
      "Pala Police Station",
      "Erattupetta Police Station",
      "Mundakayam Police Station",
      "Ponkunnam Police Station",
      "Kanjirappally Police Station",
      "Ramapuram Police Station",
      "Ayarkunnam Police Station",
      "Kaduthuruthy Police Station",
      "Gandhinagar Police Station",
      "Manarcad Police Station",
      "Nattakom Police Station",
      "Thalayolaparambu Police Station",
      "Karukachal Police Station",
    ],
  },
  Idukki: {
    name: "Idukki",
    courts: [
      "District Court, Thodupuzha",
      "Sub Court, Thodupuzha",
      "Sub Court, Devikulam",
      "Munsiff Court, Thodupuzha",
      "Munsiff Court, Peerumedu",
      "Munsiff Court, Devikulam",
      "Munsiff Court, Udumbanchola",
      "Family Court, Thodupuzha",
      "Chief Judicial Magistrate Court, Thodupuzha",
      "Sessions Court, Thodupuzha",
      "Consumer Disputes Redressal Forum, Thodupuzha",
    ],
    policeStations: [
      "Thodupuzha Police Station",
      "Idukki Police Station",
      "Munnar Police Station",
      "Adimali Police Station",
      "Devikulam Police Station",
      "Nedumkandam Police Station",
      "Peerumedu Police Station",
      "Vandiperiyar Police Station",
      "Kattappana Police Station",
      "Kumily Police Station",
      "Karimannoor Police Station",
      "Muttom Police Station",
      "Painavu Police Station",
      "Kanchiyar Police Station",
      "Upputhara Police Station",
      "Santhanpara Police Station",
      "Rajakumari Police Station",
    ],
  },
  Ernakulam: {
    name: "Ernakulam",
    courts: [
      "District Court, Ernakulam",
      "Sub Court, Ernakulam",
      "Sub Court, Aluva",
      "Sub Court, Muvattupuzha",
      "Sub Court, Perumbavoor",
      "Munsiff Court, Ernakulam",
      "Munsiff Court, Aluva",
      "Munsiff Court, Muvattupuzha",
      "Munsiff Court, Perumbavoor",
      "Munsiff Court, Kothamangalam",
      "Munsiff Court, North Paravur",
      "Munsiff Court, Angamaly",
      "Munsiff Court, Piravom",
      "Family Court, Ernakulam",
      "Chief Judicial Magistrate Court, Ernakulam",
      "Sessions Court, Ernakulam",
      "Additional District Court, Ernakulam",
      "Motor Accident Claims Tribunal, Ernakulam",
      "Consumer Disputes Redressal Forum, Ernakulam",
      "Labour Court, Ernakulam",
      "Special Court (NDPS), Ernakulam",
    ],
    policeStations: [
      "Central Police Station, Ernakulam",
      "South Police Station, Ernakulam",
      "Ernakulam North Police Station",
      "Palarivattom Police Station",
      "Thrikkakara Police Station",
      "Kalamassery Police Station",
      "Aluva Police Station",
      "Aluva East Police Station",
      "Angamaly Police Station",
      "North Paravur Police Station",
      "Perumbavoor Police Station",
      "Muvattupuzha Police Station",
      "Kothamangalam Police Station",
      "Piravom Police Station",
      "Mattancherry Police Station",
      "Fort Kochi Police Station",
      "Cheranalloor Police Station",
      "Mulavukad Police Station",
      "Harbour Police Station",
      "Hill Palace Police Station",
      "Thrippunithura Police Station",
      "Maradu Police Station",
      "Chottanikkara Police Station",
      "Infopark Police Station",
      "Binanipuram Police Station",
      "Edathala Police Station",
      "Kalady Police Station",
      "Kuruppampady Police Station",
      "Puthencruz Police Station",
      "Nedumbassery Police Station",
    ],
  },
  Thrissur: {
    name: "Thrissur",
    courts: [
      "District Court, Thrissur",
      "Sub Court, Thrissur",
      "Sub Court, Irinjalakuda",
      "Sub Court, Chavakkad",
      "Sub Court, Kodungallur",
      "Munsiff Court, Thrissur",
      "Munsiff Court, Irinjalakuda",
      "Munsiff Court, Chavakkad",
      "Munsiff Court, Kodungallur",
      "Munsiff Court, Chalakudy",
      "Munsiff Court, Kunnamkulam",
      "Munsiff Court, Wadakkancherry",
      "Family Court, Thrissur",
      "Chief Judicial Magistrate Court, Thrissur",
      "Sessions Court, Thrissur",
      "Additional District Court, Thrissur",
      "Motor Accident Claims Tribunal, Thrissur",
      "Consumer Disputes Redressal Forum, Thrissur",
    ],
    policeStations: [
      "Thrissur East Police Station",
      "Thrissur West Police Station",
      "Ollur Police Station",
      "Viyyur Police Station",
      "Peramangalam Police Station",
      "Irinjalakuda Police Station",
      "Chalakudy Police Station",
      "Kodungallur Police Station",
      "Kunnamkulam Police Station",
      "Chavakkad Police Station",
      "Guruvayoor Police Station",
      "Wadakkancherry Police Station",
      "Mala Police Station",
      "Mukundapuram Police Station",
      "Pavaratty Police Station",
      "Cherpu Police Station",
      "Anthikad Police Station",
      "Kodakara Police Station",
      "Valappad Police Station",
      "Mathilakam Police Station",
      "Puzhakkal Police Station",
      "Peringottukara Police Station",
    ],
  },
  Palakkad: {
    name: "Palakkad",
    courts: [
      "District Court, Palakkad",
      "Sub Court, Palakkad",
      "Sub Court, Ottapalam",
      "Sub Court, Mannarkad",
      "Munsiff Court, Palakkad",
      "Munsiff Court, Ottapalam",
      "Munsiff Court, Mannarkad",
      "Munsiff Court, Alathur",
      "Munsiff Court, Chittur",
      "Munsiff Court, Pattambi",
      "Family Court, Palakkad",
      "Chief Judicial Magistrate Court, Palakkad",
      "Sessions Court, Palakkad",
      "Motor Accident Claims Tribunal, Palakkad",
      "Consumer Disputes Redressal Forum, Palakkad",
    ],
    policeStations: [
      "Palakkad Town North Police Station",
      "Palakkad Town South Police Station",
      "Olavakkode Police Station",
      "Walayar Police Station",
      "Chittur Police Station",
      "Kollengode Police Station",
      "Nenmara Police Station",
      "Alathur Police Station",
      "Shoranur Police Station",
      "Ottapalam Police Station",
      "Pattambi Police Station",
      "Mannarkad Police Station",
      "Agali Police Station",
      "Attappadi Police Station",
      "Thrithala Police Station",
      "Kongad Police Station",
      "Kuzhalmannam Police Station",
      "Lakkidi Police Station",
      "Muthalamada Police Station",
      "Sreekrishnapuram Police Station",
      "Perinthalmanna Police Station",
      "Malampuzha Police Station",
    ],
  },
  Malappuram: {
    name: "Malappuram",
    courts: [
      "District Court, Manjeri",
      "Sub Court, Manjeri",
      "Sub Court, Perinthalmanna",
      "Sub Court, Tirur",
      "Sub Court, Ponnani",
      "Munsiff Court, Manjeri",
      "Munsiff Court, Perinthalmanna",
      "Munsiff Court, Tirur",
      "Munsiff Court, Ponnani",
      "Munsiff Court, Nilambur",
      "Munsiff Court, Kondotty",
      "Family Court, Manjeri",
      "Chief Judicial Magistrate Court, Manjeri",
      "Sessions Court, Manjeri",
      "Motor Accident Claims Tribunal, Manjeri",
      "Consumer Disputes Redressal Forum, Manjeri",
    ],
    policeStations: [
      "Malappuram Police Station",
      "Manjeri Police Station",
      "Perinthalmanna Police Station",
      "Tirur Police Station",
      "Ponnani Police Station",
      "Kondotty Police Station",
      "Nilambur Police Station",
      "Kottakkal Police Station",
      "Tanur Police Station",
      "Tirurangadi Police Station",
      "Valanchery Police Station",
      "Wandoor Police Station",
      "Areekode Police Station",
      "Edavanna Police Station",
      "Kalikavu Police Station",
      "Karuvarakundu Police Station",
      "Kalpakanchery Police Station",
      "Makkaraparamba Police Station",
      "Parappanangadi Police Station",
      "Vengara Police Station",
      "Melattur Police Station",
      "Mankada Police Station",
    ],
  },
  Kozhikode: {
    name: "Kozhikode",
    courts: [
      "District Court, Kozhikode",
      "Sub Court, Kozhikode",
      "Sub Court, Vatakara",
      "Sub Court, Koyilandy",
      "Munsiff Court, Kozhikode",
      "Munsiff Court, Vatakara",
      "Munsiff Court, Koyilandy",
      "Munsiff Court, Thamarassery",
      "Munsiff Court, Quilandy",
      "Family Court, Kozhikode",
      "Chief Judicial Magistrate Court, Kozhikode",
      "Sessions Court, Kozhikode",
      "Additional District Court, Kozhikode",
      "Motor Accident Claims Tribunal, Kozhikode",
      "Consumer Disputes Redressal Forum, Kozhikode",
      "Labour Court, Kozhikode",
    ],
    policeStations: [
      "Kozhikode Town North Police Station",
      "Kozhikode Town South Police Station",
      "Kasaba Police Station, Kozhikode",
      "Medical College Police Station",
      "Nadakkavu Police Station",
      "Chevayur Police Station",
      "Feroke Police Station",
      "Beypore Police Station",
      "Koyilandy Police Station",
      "Vatakara Police Station",
      "Thamarassery Police Station",
      "Mukkom Police Station",
      "Kunnamangalam Police Station",
      "Panniyankara Police Station",
      "Perambra Police Station",
      "Nadapuram Police Station",
      "Balussery Police Station",
      "Koduvally Police Station",
      "Omassery Police Station",
      "Thiruvambady Police Station",
      "Mavoor Police Station",
      "Elathur Police Station",
    ],
  },
  Wayanad: {
    name: "Wayanad",
    courts: [
      "District Court, Kalpetta",
      "Sub Court, Kalpetta",
      "Sub Court, Mananthavady",
      "Munsiff Court, Kalpetta",
      "Munsiff Court, Mananthavady",
      "Munsiff Court, Sulthan Bathery",
      "Family Court, Kalpetta",
      "Chief Judicial Magistrate Court, Kalpetta",
      "Sessions Court, Kalpetta",
      "Consumer Disputes Redressal Forum, Kalpetta",
    ],
    policeStations: [
      "Kalpetta Police Station",
      "Sulthan Bathery Police Station",
      "Mananthavady Police Station",
      "Vythiri Police Station",
      "Ambalavayal Police Station",
      "Meenangadi Police Station",
      "Panamaram Police Station",
      "Thariyode Police Station",
      "Meppadi Police Station",
      "Vellamunda Police Station",
      "Thirunelly Police Station",
      "Pulpally Police Station",
      "Noolpuzha Police Station",
      "Kenichira Police Station",
    ],
  },
  Kannur: {
    name: "Kannur",
    courts: [
      "District Court, Kannur",
      "Sub Court, Kannur",
      "Sub Court, Thalassery",
      "Sub Court, Taliparamba",
      "Munsiff Court, Kannur",
      "Munsiff Court, Thalassery",
      "Munsiff Court, Taliparamba",
      "Munsiff Court, Iritty",
      "Munsiff Court, Payyanur",
      "Family Court, Kannur",
      "Chief Judicial Magistrate Court, Kannur",
      "Sessions Court, Kannur",
      "Motor Accident Claims Tribunal, Kannur",
      "Consumer Disputes Redressal Forum, Kannur",
    ],
    policeStations: [
      "Kannur Town Police Station",
      "Thalassery Police Station",
      "Taliparamba Police Station",
      "Payyanur Police Station",
      "Mattannur Police Station",
      "Iritty Police Station",
      "Kuthuparamba Police Station",
      "Peravoor Police Station",
      "Sreekandapuram Police Station",
      "Anthoor Police Station",
      "Valapattanam Police Station",
      "Dharmadam Police Station",
      "Panoor Police Station",
      "Kelakam Police Station",
      "Koothuparamba Police Station",
      "Kannapuram Police Station",
      "Mayyil Police Station",
      "New Mahe Police Station",
      "Edakkad Police Station",
      "Chokli Police Station",
    ],
  },
  Kasaragod: {
    name: "Kasaragod",
    courts: [
      "District Court, Kasaragod",
      "Sub Court, Kasaragod",
      "Sub Court, Kanhangad",
      "Munsiff Court, Kasaragod",
      "Munsiff Court, Kanhangad",
      "Munsiff Court, Hosdurg",
      "Family Court, Kasaragod",
      "Chief Judicial Magistrate Court, Kasaragod",
      "Sessions Court, Kasaragod",
      "Consumer Disputes Redressal Forum, Kasaragod",
    ],
    policeStations: [
      "Kasaragod Police Station",
      "Kanhangad Police Station",
      "Hosdurg Police Station",
      "Bekal Police Station",
      "Uppala Police Station",
      "Manjeshwar Police Station",
      "Nileshwar Police Station",
      "Cheruvathur Police Station",
      "Rajapuram Police Station",
      "Adhur Police Station",
      "Badiadka Police Station",
      "Vellarikundu Police Station",
      "Chandera Police Station",
      "Kumbla Police Station",
      "Trikkaripur Police Station",
    ],
  },
};

export const DISTRICT_NAMES = Object.keys(KERALA_DISTRICTS);
